function build_script(task_file, result_file)

    fprintf('[MATLAB] Build script started\n');
    fprintf('[MATLAB] Task file: %s\n', task_file);

    try
        fid = fopen(task_file, 'r');
        task_json = fread(fid, '*char')';
        fclose(fid);
        task = jsondecode(task_json);
    catch ME
        write_result(result_file, -1, sprintf('Failed to read task: %s', ME.message));
        return;
    end

    model_name = task.model_name;
    slx_path = task.slx_path;
    output_dir = task.output_dir;
    lib_name = task.lib_name;

    fprintf('[MATLAB] Model: %s\n', model_name);
    fprintf('[MATLAB] SLX: %s\n', slx_path);

    try
        load_system(slx_path);
        fprintf('[MATLAB] Model loaded\n');
    catch ME
        write_result(result_file, -1, sprintf('Failed to load: %s', ME.message));
        return;
    end

    try
        set_param(model_name, 'SystemTargetFile', 'ert.tlc');
        set_param(model_name, 'TargetLang', 'C');
        set_param(model_name, 'GenerateComments', 'on');
        set_param(model_name, 'GenerateReport', 'on');
        set_param(model_name, 'GenerateCodeOnly', 'on');
        set_param(model_name, 'SolverType', 'Fixed-step');
        set_param(model_name, 'Solver', 'FixedStepDiscrete');
        set_param(model_name, 'FixedStep', '0.001');
        set_param(model_name, 'ParameterTuning', 'on');
        fprintf('[MATLAB] Configured\n');
    catch ME
        write_result(result_file, -1, sprintf('Config failed: %s', ME.message));
        return;
    end

    try
        v = version('-release');
        ver_num = str2double(v(2:5));
        if ver_num >= 2019
            cfg = coder.config('lib');
            cfg.GenCodeOnly = true;
            cfg.TargetLang = 'C';
            slbuild(model_name, cfg);
        else
            rtwbuild(model_name);
        end
        fprintf('[MATLAB] Code generated\n');
    catch ME
        write_result(result_file, -1, sprintf('Generation failed: %s', ME.message));
        return;
    end

    try
        code_dir = fullfile(output_dir, [model_name '_ert_rtw']);
        if ~exist(code_dir, 'dir')
            code_dir = output_dir;
        end
        c_files = dir(fullfile(code_dir, '*.c'));
        if isempty(c_files)
            error('No C files found');
        end

        % ---- 创建 model_rt_bridge.h (桥接头文件) ----
        bridge_h = fullfile(code_dir, 'model_rt_bridge.h');
        fid = fopen(bridge_h, 'w');
        fprintf(fid, '/* Auto-generated by build_script.m */\n');
        fprintf(fid, '#ifndef MODEL_RT_BRIDGE_H\n');
        fprintf(fid, '#define MODEL_RT_BRIDGE_H\n\n');
        fprintf(fid, '#include "%s.h"\n\n', model_name);
        fprintf(fid, 'typedef %s_U_t ModelU_t;\n', model_name);
        fprintf(fid, 'typedef %s_Y_t ModelY_t;\n\n', model_name);
        fprintf(fid, '#define MODEL_INIT_FN  %s_initialize\n', model_name);
        fprintf(fid, '#define MODEL_STEP_FN  %s_step\n', model_name);
        fprintf(fid, '#define MODEL_TERM_FN  %s_terminate\n', model_name);
        fprintf(fid, '#define MODEL_U_VAR    %s_U\n', model_name);
        fprintf(fid, '#define MODEL_Y_VAR    %s_Y\n\n', model_name);
        fprintf(fid, '#endif\n');
        fclose(fid);
        fprintf('[MATLAB] Bridge header: %s\n', bridge_h);

        % ---- 编译为独立可执行程序 ----
        hil_root = fullfile(fileparts(fileparts(output_dir)));
        custom_src_dir = fullfile(hil_root, 'c_core', 'src');
        exe_dir = fullfile(fileparts(output_dir), 'executables');
        mkdir(exe_dir);
        exe_path = fullfile(exe_dir, [model_name '_rt']);

        cmd = sprintf(['gcc -O2 -Wall -pthread ' ...
                       '-I"%s" -I"%s" ' ...
                       '-DMODEL_RT_BRIDGE_H=\\"%s\\" ' ...
                       '%s "%s/main_rt.c" ' ...
                       '"%s/model_rt_wrapper.c" ' ...
                       '"%s/local_udp.c" ' ...
                       '"%s/hal_stub.c" ' ...
                       '-lm -lrt -ljson-c -lpthread ' ...
                       '-o "%s"'], ...
            code_dir, custom_src_dir, bridge_h, ...
            gen_c_flags(code_dir, c_files), custom_src_dir, ...
            custom_src_dir, custom_src_dir, custom_src_dir, exe_path);

        fprintf('[MATLAB] Compiling: %s\n', cmd);
        [status, output] = system(cmd);
        if status ~= 0
            error('Compile failed: %s', output);
        end
        fprintf('[MATLAB] Executable created: %s\n', exe_path);
    catch ME
        write_result(result_file, -1, sprintf('Compile failed: %s', ME.message));
        return;
    end

    result = struct('code', 0, 'message', 'Build successful', ...
                    'exe_path', exe_path, 'model_name', model_name, ...
                    'timestamp', datestr(now, 'yyyy-mm-dd HH:MM:SS'));
    write_result_json(result_file, result);
    write_result_json(result_file, result);
    fprintf('[MATLAB] Build complete\n');
    bdclose(model_name);
end

function write_result_json(filename, data)
    fid = fopen(filename, 'w');
    fprintf(fid, '%s', jsonencode(data));
    fclose(fid);
end

function write_result(filename, code, message)
    data = struct('code', code, 'message', message);
    write_result_json(filename, data);
end

function flags = gen_c_flags(code_dir, c_files)
    flags = '';
    for i = 1:length(c_files)
        flags = [flags ' "' fullfile(code_dir, c_files(i).name) '"'];
    end
end