function model_path = generate_fixed_wing_model(output_dir)
%GENERATE_FIXED_WING_MODEL Contract-bound 1 ms fixed-wing HIL plant.
    if nargin < 1, output_dir = pwd; end
    if ~exist(output_dir,'dir'), mkdir(output_dir); end
    mdl = 'fixed_wing_hil'; try, close_system(mdl,0); catch, end; new_system(mdl);
    set_param(mdl,'SystemTargetFile','ert.tlc','TargetLang','C','SolverType','Fixed-step', ...
        'Solver','FixedStepDiscrete','FixedStep','0.001','StopTime','inf');
    ws = get_param(mdl,'ModelWorkspace');
    tunables = {'uav_mass_kg',2.0;'uav_inertia_xx_kgm2',0.03;'uav_inertia_yy_kgm2',0.04; ...
        'uav_inertia_zz_kgm2',0.06;'uav_linear_drag_ns_m',0.2;'uav_angular_drag_nms',0.02; ...
        'uav_wind_n_bias_mps',0;'uav_wind_e_bias_mps',0;'uav_wind_d_bias_mps',0;'uav_wing_area_m2',0.25};
    for i=1:size(tunables,1)
        p=Simulink.Parameter(tunables{i,2}); p.DataType='double'; p.CoderInfo.StorageClass='ExportedGlobal';
        assignin(ws,tunables{i,1},p);
    end
    inputs = {'throttle','roll_cmd','pitch_cmd','yaw_cmd','wind_n_mps','wind_e_mps','wind_d_mps', ...
        'pressure_pa','temperature_k','ground_height_m','gps_bias_n_m','gps_bias_e_m','gps_bias_d_m', ...
        'imu_bias_p_radps','imu_bias_q_radps','imu_bias_r_radps','motor_1_failed','motor_2_failed', ...
        'motor_3_failed','motor_4_failed','command_delay_ms','sensor_delay_ms','packet_loss_ratio'};
    for i=1:length(inputs)
        add_block('simulink/Sources/In1',[mdl '/' inputs{i}],'Port',num2str(i),'Position',[30 20+i*28 100 38+i*28]);
        if ~isempty(regexp(inputs{i},'^motor_[1-4]_failed$','once')), set_param([mdl '/' inputs{i}],'OutDataTypeStr','boolean'); end
    end
    plant=[mdl '/fixed_wing_plant']; add_block('simulink/User-Defined Functions/MATLAB Function',plant,'Position',[240 60 560 700]);
    chart=find(sfroot,'-isa','Stateflow.EMChart','Path',plant); chart.Script=plant_source();
    for i=1:size(tunables,1), d=Stateflow.Data(chart); d.Name=tunables{i,1}; d.Scope='Parameter'; end
    for i=1:length(inputs), add_line(mdl,[inputs{i} '/1'],['fixed_wing_plant/' num2str(i)],'autorouting','on'); end
    outputs={'north_m','east_m','down_m','vn_mps','ve_mps','vd_mps','q_w','q_x','q_y','q_z','p_radps','q_radps','r_radps','airborne','ax_mps2','ay_mps2','az_mps2'};
    for i=1:length(outputs)
        add_block('simulink/Sinks/Out1',[mdl '/' outputs{i}],'Port',num2str(i),'Position',[700 20+i*28 780 38+i*28]);
        add_line(mdl,['fixed_wing_plant/' num2str(i)],[outputs{i} '/1'],'autorouting','on');
    end
    model_path=fullfile(output_dir,[mdl '.slx']); save_system(mdl,model_path); close_system(mdl,0);
end

function source=plant_source()
L={ ...
'function [n,e,d,vn,ve,vd,qw,qx,qy,qz,p,q,r,air,ax,ay,az]=plant(thr,roll,pitch,yaw,wn,we,wd,pressure,temp,ground,gbn,gbe,gbd,ibp,ibq,ibr,f1,f2,f3,f4,cmd_delay,sensor_delay,loss)'; ...
'%#codegen'; ...
'persistent pos vel euler rates'; ...
'if isempty(pos), pos=zeros(3,1);vel=[12;0;0];euler=zeros(3,1);rates=zeros(3,1);end'; ...
'dt=0.001; thr=min(max(thr,0),1)*(1-double(f1))*max(0,1-loss); wind=[wn+uav_wind_n_bias_mps;we+uav_wind_e_bias_mps;wd+uav_wind_d_bias_mps];'; ...
'airvel=vel-wind; speed=max(norm(airvel),0.1); rho=min(max(pressure/(287.05*max(temp,150)),0.5),2);'; ...
'rates=rates+dt*([3*roll;2.5*pitch;1.5*yaw]-rates)./[0.18;0.22;0.3]; euler=euler+dt*rates; euler(1)=min(max(euler(1),-1.2),1.2); euler(2)=min(max(euler(2),-0.8),0.8);'; ...
'cr=cos(euler(1));sr=sin(euler(1));cp=cos(euler(2));sp=sin(euler(2));cy=cos(euler(3));sy=sin(euler(3));'; ...
'R=[cy*cp,cy*sp*sr-sy*cr,cy*sp*cr+sy*sr;sy*cp,sy*sp*sr+cy*cr,sy*sp*cr-cy*sr;-sp,cp*sr,cp*cr];'; ...
'thrust=18*thr; lift=0.5*rho*uav_wing_area_m2*speed*speed*(0.16+1.1*(-euler(2))); drag=uav_linear_drag_ns_m*speed*speed; force=R*[thrust-drag;0;-lift]+[0;0;uav_mass_kg*9.80665]; acc=force/uav_mass_kg;'; ...
'vel=vel+dt*acc;pos=pos+dt*vel; ground_d=-ground; if pos(3)>ground_d, pos(3)=ground_d;vel(3)=min(vel(3),0);end'; ...
'h=euler(3)/2;t=euler(2)/2;b=euler(1)/2; qw=cos(b)*cos(t)*cos(h)+sin(b)*sin(t)*sin(h);qx=sin(b)*cos(t)*cos(h)-cos(b)*sin(t)*sin(h);qy=cos(b)*sin(t)*cos(h)+sin(b)*cos(t)*sin(h);qz=cos(b)*cos(t)*sin(h)-sin(b)*sin(t)*cos(h);'; ...
'delay=min(max(sensor_delay,0),1000)*0.001;reported=pos-delay*vel+[gbn;gbe;gbd]; n=reported(1);e=reported(2);d=reported(3);vn=vel(1);ve=vel(2);vd=vel(3);p=rates(1)+ibp;q=rates(2)+ibq;r=rates(3)+ibr;air=pos(3)<ground_d-0.05;ax=acc(1);ay=acc(2);az=acc(3);'; ...
'end'}; source=strjoin(L,sprintf('\n'));
end
