function model_path = generate_quadrotor_model(output_dir)
%GENERATE_QUADROTOR_MODEL Create the contract-bound four-rotor HIL plant.
% The plant uses 17 discrete states: NED position/velocity, a FRD-to-NED
% quaternion, FRD angular rates and four first-order motor responses.
    if nargin < 1, output_dir = pwd; end
    if ~exist(output_dir, 'dir'), mkdir(output_dir); end
    mdl = 'quadrotor_hil';
    try, close_system(mdl, 0); catch, end
    new_system(mdl);
    cleanup = onCleanup(@() close_if_loaded(mdl)); %#ok<NASGU>
    set_param(mdl, 'SystemTargetFile', 'ert.tlc');
    set_param(mdl, 'TargetLang', 'C');
    set_param(mdl, 'SolverType', 'Fixed-step');
    set_param(mdl, 'Solver', 'FixedStepDiscrete');
    set_param(mdl, 'FixedStep', '0.001');
    set_param(mdl, 'StopTime', 'inf');
    set_param(mdl, 'SaveTime', 'off', 'SaveOutput', 'off');

    workspace = get_param(mdl, 'ModelWorkspace');
    tunables = { ...
        'uav_mass_kg', 1.5; ...
        'uav_inertia_xx_kgm2', 0.029; ...
        'uav_inertia_yy_kgm2', 0.029; ...
        'uav_inertia_zz_kgm2', 0.055; ...
        'uav_thrust_coefficient_n', 4.2; ...
        'uav_moment_coefficient_nm', 0.08; ...
        'uav_linear_drag_ns_m', 0.25; ...
        'uav_angular_drag_nms', 0.02; ...
        'uav_wind_n_bias_mps', 0.0; ...
        'uav_wind_e_bias_mps', 0.0; ...
        'uav_wind_d_bias_mps', 0.0; ...
        'uav_motor_efficiency', 1.0};
    for i = 1:size(tunables, 1)
        value = Simulink.Parameter(tunables{i, 2});
        value.DataType = 'double';
        value.CoderInfo.StorageClass = 'ExportedGlobal';
        assignin(workspace, tunables{i, 1}, value);
        assignin('base', tunables{i, 1}, value);
    end

    inputs = {'motor_command','wind_n_mps','wind_e_mps','wind_d_mps', ...
        'pressure_pa','temperature_k','ground_height_m', ...
        'gps_bias_n_m','gps_bias_e_m','gps_bias_d_m', ...
        'imu_bias_p_radps','imu_bias_q_radps','imu_bias_r_radps', ...
        'motor_1_failed','motor_2_failed','motor_3_failed','motor_4_failed', ...
        'command_delay_ms','sensor_delay_ms','packet_loss_ratio'};
    for i = 1:length(inputs)
        path = [mdl '/' inputs{i}];
        add_block('simulink/Sources/In1', path, 'Port', num2str(i), ...
            'Position', [30, 25 + 35*i, 120, 45 + 35*i]);
        if strcmp(inputs{i}, 'motor_command')
            set_param(path, 'PortDimensions', '4');
        elseif ~isempty(regexp(inputs{i}, '^motor_[1-4]_failed$', 'once'))
            set_param(path, 'OutDataTypeStr', 'boolean');
        end
    end

    plant_path = [mdl '/four_rotor_physical_plant'];
    add_block('simulink/User-Defined Functions/MATLAB Function', plant_path, ...
        'Position', [260, 70, 560, 700]);
    stateflow_root = sfroot;
    chart = find(stateflow_root, '-isa', 'Stateflow.EMChart', 'Path', plant_path);
    if isempty(chart), error('Cannot find generated MATLAB Function block'); end
    chart.Script = plant_source();
    for i = 1:size(tunables, 1)
        parameter = Stateflow.Data(chart);
        parameter.Name = tunables{i, 1};
        parameter.Scope = 'Parameter';
    end
    for i = 1:length(inputs)
        add_line(mdl, [inputs{i} '/1'], ['four_rotor_physical_plant/' num2str(i)], ...
            'autorouting', 'on');
    end

    outputs = {'north_m','east_m','down_m','vn_mps','ve_mps','vd_mps', ...
        'q_w','q_x','q_y','q_z','p_radps','q_radps','r_radps','airborne', ...
        'ax_mps2','ay_mps2','az_mps2'};
    for i = 1:length(outputs)
        path = [mdl '/' outputs{i}];
        add_block('simulink/Sinks/Out1', path, 'Port', num2str(i), ...
            'Position', [700, 25 + 35*i, 790, 45 + 35*i]);
        add_line(mdl, ['four_rotor_physical_plant/' num2str(i)], [outputs{i} '/1'], ...
            'autorouting', 'on');
    end

    model_path = fullfile(output_dir, [mdl '.slx']);
    save_system(mdl, model_path);
    close_system(mdl, 0);
end

function source = plant_source()
    lines = { ...
        'function [north_m,east_m,down_m,vn_mps,ve_mps,vd_mps,q_w,q_x,q_y,q_z,p_radps,q_radps,r_radps,airborne,ax_mps2,ay_mps2,az_mps2] = plant(motor_command,wind_n_mps,wind_e_mps,wind_d_mps,pressure_pa,temperature_k,ground_height_m,gps_bias_n_m,gps_bias_e_m,gps_bias_d_m,imu_bias_p_radps,imu_bias_q_radps,imu_bias_r_radps,motor_1_failed,motor_2_failed,motor_3_failed,motor_4_failed,command_delay_ms,sensor_delay_ms,packet_loss_ratio)'; ...
        '%#codegen'; ...
        'persistent position_ned velocity_ned quaternion_frd_to_ned body_rates motor_response'; ...
        'if isempty(position_ned)'; ...
        '    position_ned = zeros(3,1);'; ...
        '    velocity_ned = zeros(3,1);'; ...
        '    quaternion_frd_to_ned = [1.0;0.0;0.0;0.0];'; ...
        '    body_rates = zeros(3,1);'; ...
        '    motor_response = zeros(4,1);'; ...
        'end'; ...
        'dt = 0.001;'; ...
        'command = min(max(motor_command(:),0.0),1.0);'; ...
        'failed = double([motor_1_failed;motor_2_failed;motor_3_failed;motor_4_failed]);'; ...
        'command = command .* (1.0-failed) .* max(0.0,1.0-packet_loss_ratio);'; ...
        'motor_time_constant = 0.035 + min(max(command_delay_ms,0.0),1000.0)*0.001;'; ...
        'motor_target = command .* uav_motor_efficiency;'; ...
        'motor_response = motor_response + dt .* (motor_target-motor_response) ./ motor_time_constant;'; ...
        'motor_response = min(max(motor_response,0.0),1.2);'; ...
        'safe_pressure = max(pressure_pa,1000.0);'; ...
        'safe_temperature = max(temperature_k,150.0);'; ...
        'density_scale = min(max((safe_pressure/(287.05*safe_temperature))/1.225,0.5),1.5);'; ...
        'motor_thrust = uav_thrust_coefficient_n .* motor_response.^2 .* density_scale;'; ...
        'q0=quaternion_frd_to_ned(1); q1=quaternion_frd_to_ned(2);'; ...
        'q2=quaternion_frd_to_ned(3); q3=quaternion_frd_to_ned(4);'; ...
        ['rotation_frd_to_ned = [1-2*(q2*q2+q3*q3),2*(q1*q2-q0*q3),2*(q1*q3+q0*q2);' ...
         '    2*(q1*q2+q0*q3),1-2*(q1*q1+q3*q3),2*(q2*q3-q0*q1);' ...
         '    2*(q1*q3-q0*q2),2*(q2*q3+q0*q1),1-2*(q1*q1+q2*q2)];']; ...
        'wind_ned = [wind_n_mps+uav_wind_n_bias_mps;wind_e_mps+uav_wind_e_bias_mps;wind_d_mps+uav_wind_d_bias_mps];'; ...
        'relative_wind_ned = velocity_ned-wind_ned;'; ...
        'gravity_ned = [0.0;0.0;9.80665];'; ...
        'thrust_force_ned = rotation_frd_to_ned * [0.0;0.0;-sum(motor_thrust)];'; ...
        'drag_force_ned = -uav_linear_drag_ns_m .* relative_wind_ned;'; ...
        'acceleration_ned = gravity_ned + (thrust_force_ned+drag_force_ned)./uav_mass_kg;'; ...
        'arm_over_root_two = 0.23/sqrt(2.0);'; ...
        ['x_frame_moment = arm_over_root_two .* [' ...
         'motor_thrust(1)-motor_thrust(2)-motor_thrust(3)+motor_thrust(4);' ...
         'motor_thrust(1)+motor_thrust(2)-motor_thrust(3)-motor_thrust(4);0.0];']; ...
        'x_frame_moment(3) = uav_moment_coefficient_nm * (-motor_response(1)^2+motor_response(2)^2-motor_response(3)^2+motor_response(4)^2);'; ...
        'inertia = [uav_inertia_xx_kgm2;uav_inertia_yy_kgm2;uav_inertia_zz_kgm2];'; ...
        'angular_momentum = inertia .* body_rates;'; ...
        'angular_acceleration = (x_frame_moment-cross(body_rates,angular_momentum)-uav_angular_drag_nms.*body_rates)./inertia;'; ...
        'velocity_ned = velocity_ned + dt.*acceleration_ned;'; ...
        'position_ned = position_ned + dt.*velocity_ned;'; ...
        'body_rates = body_rates + dt.*angular_acceleration;'; ...
        'omega_p=body_rates(1); omega_q=body_rates(2); omega_r=body_rates(3);'; ...
        ['quaternion_derivative = 0.5.*[-q1*omega_p-q2*omega_q-q3*omega_r;' ...
         '    q0*omega_p+q2*omega_r-q3*omega_q;' ...
         '    q0*omega_q+q3*omega_p-q1*omega_r;' ...
         '    q0*omega_r+q1*omega_q-q2*omega_p];']; ...
        'quaternion_frd_to_ned = quaternion_frd_to_ned + dt.*quaternion_derivative;'; ...
        'quaternion_frd_to_ned = quaternion_frd_to_ned ./ max(norm(quaternion_frd_to_ned),1.0e-12);'; ...
        'ground_down_m = -ground_height_m;'; ...
        'if position_ned(3) > ground_down_m'; ...
        '    position_ned(3) = ground_down_m;'; ...
        '    velocity_ned(3) = min(velocity_ned(3),0.0);'; ...
        'end'; ...
        'sensor_delay_s = min(max(sensor_delay_ms,0.0),1000.0)*0.001;'; ...
        'reported_position = position_ned-sensor_delay_s.*velocity_ned+[gps_bias_n_m;gps_bias_e_m;gps_bias_d_m];'; ...
        'reported_rates = body_rates-sensor_delay_s.*angular_acceleration+[imu_bias_p_radps;imu_bias_q_radps;imu_bias_r_radps];'; ...
        'north_m=reported_position(1); east_m=reported_position(2); down_m=reported_position(3);'; ...
        'vn_mps=velocity_ned(1); ve_mps=velocity_ned(2); vd_mps=velocity_ned(3);'; ...
        'q_w=quaternion_frd_to_ned(1); q_x=quaternion_frd_to_ned(2);'; ...
        'q_y=quaternion_frd_to_ned(3); q_z=quaternion_frd_to_ned(4);'; ...
        'p_radps=reported_rates(1); q_radps=reported_rates(2); r_radps=reported_rates(3);'; ...
        'airborne = position_ned(3) < ground_down_m-0.05;'; ...
        'ax_mps2=acceleration_ned(1); ay_mps2=acceleration_ned(2); az_mps2=acceleration_ned(3);'; ...
        'end'};
    source = strjoin(lines, sprintf('\n'));
end

function close_if_loaded(model_name)
    if bdIsLoaded(model_name), close_system(model_name, 0); end
end
