function model_path = generate_multirotor_model(output_dir, motor_count)
%GENERATE_MULTIROTOR_MODEL Generate a contract-bound N-motor discrete plant.
    if nargin<1, output_dir=pwd; end
    if nargin<2, motor_count=6; end
    if motor_count<4 || motor_count>32 || floor(motor_count)~=motor_count, error('motor_count must be integer 4..32'); end
    if ~exist(output_dir,'dir'),mkdir(output_dir);end; mdl=sprintf('multirotor_%d_hil',motor_count); try,close_system(mdl,0);catch,end;new_system(mdl);
    set_param(mdl,'SystemTargetFile','ert.tlc','TargetLang','C','SolverType','Fixed-step','Solver','FixedStepDiscrete','FixedStep','0.001','StopTime','inf');
    ws=get_param(mdl,'ModelWorkspace'); names={'uav_mass_kg',1.5;'uav_inertia_xx_kgm2',.03;'uav_inertia_yy_kgm2',.03;'uav_inertia_zz_kgm2',.05;'uav_linear_drag_ns_m',.2;'uav_angular_drag_nms',.02;'uav_wind_n_bias_mps',0;'uav_wind_e_bias_mps',0;'uav_wind_d_bias_mps',0;'uav_thrust_coefficient_n',4.2};
    for i=1:size(names,1),p=Simulink.Parameter(names{i,2});p.DataType='double';p.CoderInfo.StorageClass='ExportedGlobal';assignin(ws,names{i,1},p);end
    ins={'motor_command','wind_n_mps','wind_e_mps','wind_d_mps','pressure_pa','temperature_k','ground_height_m','gps_bias_n_m','gps_bias_e_m','gps_bias_d_m','imu_bias_p_radps','imu_bias_q_radps','imu_bias_r_radps','motor_1_failed','motor_2_failed','motor_3_failed','motor_4_failed','command_delay_ms','sensor_delay_ms','packet_loss_ratio'};
    for i=1:length(ins),add_block('simulink/Sources/In1',[mdl '/' ins{i}],'Port',num2str(i),'Position',[20 20+i*25 90 36+i*25]);if i==1,set_param([mdl '/' ins{i}],'PortDimensions',num2str(motor_count));elseif ~isempty(regexp(ins{i},'^motor_[1-4]_failed$','once')),set_param([mdl '/' ins{i}],'OutDataTypeStr','boolean');end,end
    plant=[mdl '/n_motor_plant'];add_block('simulink/User-Defined Functions/MATLAB Function',plant,'Position',[220 60 520 650]);chart=find(sfroot,'-isa','Stateflow.EMChart','Path',plant);chart.Script=source(motor_count);for i=1:size(names,1),d=Stateflow.Data(chart);d.Name=names{i,1};d.Scope='Parameter';end
    for i=1:length(ins),add_line(mdl,[ins{i} '/1'],['n_motor_plant/' num2str(i)],'autorouting','on');end
    outs={'north_m','east_m','down_m','vn_mps','ve_mps','vd_mps','q_w','q_x','q_y','q_z','p_radps','q_radps','r_radps','airborne','ax_mps2','ay_mps2','az_mps2'};for i=1:length(outs),add_block('simulink/Sinks/Out1',[mdl '/' outs{i}],'Port',num2str(i),'Position',[650 20+i*25 740 36+i*25]);add_line(mdl,['n_motor_plant/' num2str(i)],[outs{i} '/1'],'autorouting','on');end
    model_path=fullfile(output_dir,[mdl '.slx']);save_system(mdl,model_path);close_system(mdl,0);
end
function s=source(N)
h=sprintf(['function [n,e,d,vn,ve,vd,qw,qx,qy,qz,p,q,r,air,ax,ay,az]=plant(m,wn,we,wd,pr,te,g,gbn,gbe,gbd,ibp,ibq,ibr,f1,f2,f3,f4,cd,sd,loss)\n%%#codegen\npersistent x v a w\nif isempty(x),x=zeros(3,1);v=zeros(3,1);a=zeros(3,1);w=zeros(%d,1);end\ndt=.001;c=min(max(m(:),0),1);c(1)=c(1)*(1-double(f1));c(2)=c(2)*(1-double(f2));c(3)=c(3)*(1-double(f3));c(4)=c(4)*(1-double(f4));w=w+dt*(c*(1-loss)-w)/(.035+min(max(cd,0),1000)*.001);\nT=uav_thrust_coefficient_n*sum(w.^2);mom=zeros(3,1);for k=1:%d,ang=2*pi*(k-1)/%d;tk=uav_thrust_coefficient_n*w(k)^2;mom(1)=mom(1)+sin(ang)*tk*.23;mom(2)=mom(2)-cos(ang)*tk*.23;mom(3)=mom(3)+(-1)^k*.02*w(k)^2;end\na=a+dt*(mom-[uav_angular_drag_nms;uav_angular_drag_nms;uav_angular_drag_nms].*a)./[uav_inertia_xx_kgm2;uav_inertia_yy_kgm2;uav_inertia_zz_kgm2];R=[1 -a(3)*dt a(2)*dt;a(3)*dt 1 -a(1)*dt;-a(2)*dt a(1)*dt 1];acc=[0;0;9.80665]+R*[0;0;-T]/uav_mass_kg-uav_linear_drag_ns_m*(v-[wn+uav_wind_n_bias_mps;we+uav_wind_e_bias_mps;wd+uav_wind_d_bias_mps])/uav_mass_kg;v=v+dt*acc;x=x+dt*v;if x(3)>-g,x(3)=-g;v(3)=min(v(3),0);end\nqw=1;qx=0;qy=0;qz=0;n=x(1)+gbn;e=x(2)+gbe;d=x(3)+gbd;vn=v(1);ve=v(2);vd=v(3);p=a(1)+ibp;q=a(2)+ibq;r=a(3)+ibr;air=x(3)<-g-.05;ax=acc(1);ay=acc(2);az=acc(3);\nend'],N,N,N);s=h;end
