/* Auto-generated by build_script.m V2 */
#ifndef HIL_MODEL_RT_BRIDGE_GENERATED_H
#define HIL_MODEL_RT_BRIDGE_GENERATED_H

#include "hil_test_model.h"

typedef ExtU_hil_test_model_T ModelU_t;
#define MODEL_U_T_DEFINED 1
typedef ExtY_hil_test_model_T ModelY_t;

#define MODEL_Y_T_DEFINED 1

#define MODEL_INIT_FN  hil_test_model_initialize
#define MODEL_STEP_FN  hil_test_model_step
#define MODEL_TERM_FN  hil_test_model_terminate
#define MODEL_U_VAR    hil_test_model_U
#define MODEL_Y_VAR    hil_test_model_Y

#endif
