/* Auto-generated by build_script.m V2 */
/* Model: hil_test_model */
#ifndef MODEL_MAPPING_H
#define MODEL_MAPPING_H

/* ---- ModelU_t field mapping ---- */
/* Standard name → actual field name */
/* #define MODEL_U_alt_init NOT_PRESENT */
#define HAS_U_alt_init 0
/* #define MODEL_U_cmd_duration NOT_PRESENT */
#define HAS_U_cmd_duration 0
#define MODEL_U_cmd_mode cmd_mode
#define HAS_U_cmd_mode 1
#define MODEL_U_cmd_speed cmd_speed
#define HAS_U_cmd_speed 1
#define MODEL_U_cmd_x cmd_x
#define HAS_U_cmd_x 1
#define MODEL_U_cmd_y cmd_y
#define HAS_U_cmd_y 1
#define MODEL_U_cmd_yaw cmd_yaw
#define HAS_U_cmd_yaw 1
#define MODEL_U_cmd_z cmd_z
#define HAS_U_cmd_z 1
/* #define MODEL_U_init_x NOT_PRESENT */
#define HAS_U_init_x 0
/* #define MODEL_U_init_y NOT_PRESENT */
#define HAS_U_init_y 0
/* #define MODEL_U_lat_init NOT_PRESENT */
#define HAS_U_lat_init 0
/* #define MODEL_U_lon_init NOT_PRESENT */
#define HAS_U_lon_init 0
/* #define MODEL_U_max_height NOT_PRESENT */
#define HAS_U_max_height 0
/* #define MODEL_U_max_speed NOT_PRESENT */
#define HAS_U_max_speed 0
/* #define MODEL_U_min_height NOT_PRESENT */
#define HAS_U_min_height 0
/* #define MODEL_U_min_speed NOT_PRESENT */
#define HAS_U_min_speed 0
/* #define MODEL_U_pitch_init NOT_PRESENT */
#define HAS_U_pitch_init 0
/* #define MODEL_U_roll_init NOT_PRESENT */
#define HAS_U_roll_init 0
/* #define MODEL_U_yaw_init NOT_PRESENT */
#define HAS_U_yaw_init 0
/* ---- ModelU_t ALL fields (including model-specific tunables) ---- */

/* ---- Safe standard input writers ---- */
#define MODEL_WRITE_alt_init(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_cmd_duration(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_cmd_mode(u_ptr, value) do { (u_ptr)->cmd_mode = (value); } while (0)
#define MODEL_WRITE_cmd_speed(u_ptr, value) do { (u_ptr)->cmd_speed = (value); } while (0)
#define MODEL_WRITE_cmd_x(u_ptr, value) do { (u_ptr)->cmd_x = (value); } while (0)
#define MODEL_WRITE_cmd_y(u_ptr, value) do { (u_ptr)->cmd_y = (value); } while (0)
#define MODEL_WRITE_cmd_yaw(u_ptr, value) do { (u_ptr)->cmd_yaw = (value); } while (0)
#define MODEL_WRITE_cmd_z(u_ptr, value) do { (u_ptr)->cmd_z = (value); } while (0)
#define MODEL_WRITE_init_x(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_init_y(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_lat_init(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_lon_init(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_max_height(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_max_speed(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_min_height(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_min_speed(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_pitch_init(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_roll_init(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)
#define MODEL_WRITE_yaw_init(u_ptr, value) do { (void)(u_ptr); (void)(value); } while (0)

/* ---- ModelY_t field mapping ---- */
/* Standard name → actual field name */
/* #define MODEL_Y_acc_x NOT_PRESENT */
#define HAS_Y_acc_x 0
/* #define MODEL_Y_acc_y NOT_PRESENT */
#define HAS_Y_acc_y 0
/* #define MODEL_Y_acc_z NOT_PRESENT */
#define HAS_Y_acc_z 0
#define MODEL_Y_airborne airborne
#define HAS_Y_airborne 1
/* #define MODEL_Y_alt NOT_PRESENT */
#define HAS_Y_alt 0
/* #define MODEL_Y_lat NOT_PRESENT */
#define HAS_Y_lat 0
/* #define MODEL_Y_lon NOT_PRESENT */
#define HAS_Y_lon 0
#define MODEL_Y_pitch Theta
#define HAS_Y_pitch 1
#define MODEL_Y_pos_x X
#define HAS_Y_pos_x 1
#define MODEL_Y_pos_y Y
#define HAS_Y_pos_y 1
#define MODEL_Y_pos_z Z
#define HAS_Y_pos_z 1
#define MODEL_Y_roll Phi
#define HAS_Y_roll 1
#define MODEL_Y_vel_x vx
#define HAS_Y_vel_x 1
#define MODEL_Y_vel_y vy
#define HAS_Y_vel_y 1
#define MODEL_Y_vel_z vz
#define HAS_Y_vel_z 1
#define MODEL_Y_yaw Psi
#define HAS_Y_yaw 1

/* ---- Safe state readers: missing optional fields use defaults ---- */
#define MODEL_READ_pos_x(y_ptr) ((y_ptr)->X)
#define MODEL_READ_pos_y(y_ptr) ((y_ptr)->Y)
#define MODEL_READ_pos_z(y_ptr) ((y_ptr)->Z)
#define MODEL_READ_roll(y_ptr) ((y_ptr)->Phi)
#define MODEL_READ_pitch(y_ptr) ((y_ptr)->Theta)
#define MODEL_READ_yaw(y_ptr) ((y_ptr)->Psi)
#define MODEL_READ_vel_x(y_ptr) ((y_ptr)->vx)
#define MODEL_READ_vel_y(y_ptr) ((y_ptr)->vy)
#define MODEL_READ_vel_z(y_ptr) ((y_ptr)->vz)
#define MODEL_READ_lat(y_ptr) (39.9)
#define MODEL_READ_lon(y_ptr) (116.4)
#define MODEL_READ_alt(y_ptr) (100.0)
#define MODEL_READ_acc_x(y_ptr) (0.0f)
#define MODEL_READ_acc_y(y_ptr) (0.0f)
#define MODEL_READ_acc_z(y_ptr) (0.0f)
#define MODEL_READ_airborne(y_ptr) ((y_ptr)->airborne)

#endif /* MODEL_MAPPING_H */
