/* Auto-generated by build_script.m V2 */
#ifndef MODEL_CONFIG_H
#define MODEL_CONFIG_H

#include "model_mapping.h"

/* Model identity */
#define MODEL_NAME "hil_test_model"
#define MODEL_SLX "/home/user/桌面/hil_simulation/test_output/hil_test_model.slx"
#define MODEL_ADAPTED 0

/* Defaults for optional fields */
#define MODEL_DEFAULT_POS_X 0.0
#define MODEL_DEFAULT_POS_Y 0.0
#define MODEL_DEFAULT_POS_Z 10.0
#define MODEL_DEFAULT_ROLL  0.0f
#define MODEL_DEFAULT_PITCH 0.0f
#define MODEL_DEFAULT_YAW   0.0f

/* Runtime dispatch table — maps string key → byte offset into ModelU_t */
#define MODEL_U_TUNABLE_COUNT 6
/* All fields: cmd_x, cmd_y, cmd_z, cmd_yaw, cmd_mode, cmd_speed */
#include <stddef.h>  /* for offsetof */
struct _tunable_entry { const char* name; size_t offset; };
static const struct _tunable_entry MODEL_U_TUNABLE_TABLE[] = {
    {"cmd_x", offsetof(ModelU_t, cmd_x)},
    {"cmd_y", offsetof(ModelU_t, cmd_y)},
    {"cmd_z", offsetof(ModelU_t, cmd_z)},
    {"cmd_yaw", offsetof(ModelU_t, cmd_yaw)},
    {"cmd_mode", offsetof(ModelU_t, cmd_mode)},
    {"cmd_speed", offsetof(ModelU_t, cmd_speed)},
};

#endif /* MODEL_CONFIG_H */
