#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include <sched.h>
#include <time.h>
#include <pthread.h>
#include <sys/mman.h>
#include <inttypes.h>
#include <json-c/json.h>

#include "flight_state.h"
#include "model_rt_wrapper.h"
#include "hal_stub.h"
#include "local_udp.h"

/* model_config.h is generated by build_script.m, provides:
 *   MODEL_NAME, MODEL_ADAPTED
 *   MODEL_U_xxx / HAS_U_xxx  macros
 *   MODEL_Y_xxx / HAS_Y_xxx  macros
 *   MODEL_DEFAULT_xxx  fallback values
 *   MODEL_U_TUNABLE_TABLE  string-offset dispatch table
 */
#include "model_config.h"

#define STEP_NS 1000000LL
#define UDP_CMD_PORT 9997
#define UDP_STATUS_PORT 9998
#define SEND_INTERVAL 20   /* 50Hz = 1000/20 */

static volatile int running = 1;
static FlightState_t current_state;
static ModelInput_t model_params = { .init_lat = 39.9, .init_lon = 116.4, .init_alt = 100.0 };
static int model_initialized = 0;
static int _cmd_mode_snapshot = 0;
static int _last_cmd_mode_written = 0;  /* non-zero only on the step cmd was set */

/* ---- V2.0 waypoint queue ---- */
static struct { double x, y, height, speed; } _wp_queue[MAX_WAYPOINTS];
static int _wp_count = 0;
static int _wp_current = 0;
static int _wp_active = 0;
static char _mission_id[256] = {0};

/* ---- angular velocity calculation ---- */
static float _prev_roll = 0.0f, _prev_pitch = 0.0f, _prev_yaw = 0.0f;

/* ---- Field access helpers (uses generated macros) ---- */

/* Get output field value from ModelY_t, with compile-time fallback */
#define MODEL_Y_GET(y_ptr, name, default_val) \
    _Generic((default_val), \
        double: MODEL_Y_GET_DOUBLE(y_ptr, name, default_val), \
        float:  MODEL_Y_GET_FLOAT(y_ptr, name, default_val), \
        int:    MODEL_Y_GET_INT(y_ptr, name, default_val) \
    )

#define MODEL_Y_GET_DOUBLE(y_ptr, name, default_val) \
    (HAS_Y_##name ? (y_ptr)->MODEL_Y_##name : (default_val))

#define MODEL_Y_GET_FLOAT(y_ptr, name, default_val) \
    (HAS_Y_##name ? (y_ptr)->MODEL_Y_##name : (default_val))

#define MODEL_Y_GET_INT(y_ptr, name, default_val) \
    (HAS_Y_##name ? (y_ptr)->MODEL_Y_##name : (default_val))

/* Set input field on ModelU_t */
#define MODEL_U_SET(u_ptr, name, value) do { \
    if (HAS_U_##name) (u_ptr)->MODEL_U_##name = (value); \
} while(0)

/* Runtime dispatch: set any field by string name.
   The dispatch table (MODEL_U_TUNABLE_TABLE) is generated by build_script.m
   as a static array of { "name", offsetof(ModelU_t, name) } entries. */
static void model_u_set_by_name(ModelU_t* u, const char* name, double value) {
    /* Try dispatch table first */
    for (int i = 0; i < MODEL_U_TUNABLE_COUNT; i++) {
        if (strcmp(MODEL_U_TUNABLE_TABLE[i].name, name) == 0) {
            char* base = (char*)u;
            *(double*)(base + MODEL_U_TUNABLE_TABLE[i].offset) = value;
            return;
        }
    }
    /* Not a tunable field — silently ignored (no matching Inport) */
}

void signal_handler(int sig) {
    printf("\n[Main] Received signal %d, exiting...\n", sig);
    running = 0;
}

/* ---- V2.0 flight_state derivation ---- */
static uint8_t _fs = 0;  /* persistent, updated each SEND_INTERVAL */
static uint8_t derive_flight_state(int airborne, double pos_z, int wp_active) {
    /* Transition from taking_off once airborne */
    if (_fs == 1 && airborne && pos_z >= 0.5) _fs = 3; /* -> hovering */
    /* Transition from landing once on ground */
    if (_fs == 4 && !airborne && pos_z < 0.5) _fs = 5; /* -> landed */
    /* Transition from hovering to landed if not airborne */
    if (_fs == 3 && !airborne && pos_z < 0.5) _fs = 5;
    /* landed -> ready transitions are handled by takeoff command */

    /* Check for new commands written this step (set via write trigger marker) */
    if (_last_cmd_mode_written) {
        int m = _last_cmd_mode_written;
        _last_cmd_mode_written = 0;
        if (m == 1) { _fs = 1; return _fs; }   /* taking_off */
        if (m == 2) { _fs = 4; return _fs; }   /* landing */
        if (m == 3) { _fs = 3; return _fs; }   /* hovering */
    }

    /* Steady-state derivation */
    if (!airborne && pos_z < 0.5) { _fs = 5; return _fs; } /* landed */
    if (!airborne && pos_z >= 0.5) { _fs = 0; return _fs; } /* ready */
    if (wp_active) { _fs = 2; return _fs; } /* flying (waypoint mode) */
    if (airborne && _fs != 2) { _fs = 3; return _fs; } /* hovering */
    if (airborne) { _fs = 2; return _fs; }  /* flying */
    _fs = 0;
    return _fs; /* ready */
}

static const char* flight_state_str(uint8_t fs) {
    switch (fs) {
        case 0: return "ready";
        case 1: return "taking_off";
        case 2: return "flying";
        case 3: return "hovering";
        case 4: return "landing";
        case 5: return "landed";
        case 6: return "fault";
        default: return "ready";
    }
}

static int parse_command(const char* json_str) {
    if (!json_str) return -1;
    struct json_object *root, *params_obj, *cmd_obj;
    root = json_tokener_parse(json_str);
    if (!root) return -1;

    const char* cmd = NULL;
    json_object_object_get_ex(root, "cmd", &cmd_obj);
    if (cmd_obj) cmd = json_object_get_string(cmd_obj);

    /* ---- init_sim ---- */
    if (cmd && strcmp(cmd, "init_sim") == 0) {
        json_object_object_get_ex(root, "params", &params_obj);
        if (params_obj) {
            json_object_object_foreach(params_obj, key, val) {
                if (strcmp(key, "initial_lat") == 0) model_params.init_lat = json_object_get_double(val);
                else if (strcmp(key, "initial_lon") == 0) model_params.init_lon = json_object_get_double(val);
                else if (strcmp(key, "initial_alt") == 0) model_params.init_alt = json_object_get_double(val);
                else if (strcmp(key, "initial_roll") == 0) model_params.init_roll = json_object_get_double(val);
                else if (strcmp(key, "initial_pitch") == 0) model_params.init_pitch = json_object_get_double(val);
                else if (strcmp(key, "initial_yaw") == 0) model_params.init_yaw = json_object_get_double(val);
                else if (strcmp(key, "init_x") == 0) model_params.init_x = json_object_get_double(val);
                else if (strcmp(key, "init_y") == 0) model_params.init_y = json_object_get_double(val);
                else if (strcmp(key, "min_speed") == 0) model_params.min_speed = (float)json_object_get_double(val);
                else if (strcmp(key, "max_speed") == 0) model_params.max_speed = (float)json_object_get_double(val);
                else if (strcmp(key, "min_height") == 0) model_params.min_height = (float)json_object_get_double(val);
                else if (strcmp(key, "max_height") == 0) model_params.max_height = (float)json_object_get_double(val);
            }
        }
        ModelU_t* U = model_get_input();
        if (U) {
            MODEL_U_SET(U, lat_init, model_params.init_lat);
            MODEL_U_SET(U, lon_init, model_params.init_lon);
            MODEL_U_SET(U, alt_init, model_params.init_alt);
            MODEL_U_SET(U, roll_init, model_params.init_roll);
            MODEL_U_SET(U, pitch_init, model_params.init_pitch);
            MODEL_U_SET(U, yaw_init, model_params.init_yaw);
            MODEL_U_SET(U, init_x, model_params.init_x);
            MODEL_U_SET(U, init_y, model_params.init_y);
            MODEL_U_SET(U, min_speed, model_params.min_speed);
            MODEL_U_SET(U, max_speed, model_params.max_speed);
            MODEL_U_SET(U, min_height, model_params.min_height);
            MODEL_U_SET(U, max_height, model_params.max_height);
            model_initialized = 1;
            printf("[Main] Model initialized\n");
        }
        json_object_put(root);
        return 0;
    }

    /* ---- load_mission ---- */
    if (cmd && strcmp(cmd, "load_mission") == 0) {
        json_object_object_get_ex(root, "params", &params_obj);
        if (params_obj) {
            struct json_object *wps_obj, *wp_obj;
            json_object_object_get_ex(params_obj, "mission_id", &cmd_obj);
            if (cmd_obj) {
                strncpy(_mission_id, json_object_get_string(cmd_obj), sizeof(_mission_id) - 1);
            }
            json_object_object_get_ex(params_obj, "waypoints", &wps_obj);
            int n = json_object_array_length(wps_obj);
            _wp_count = (n < MAX_WAYPOINTS) ? n : MAX_WAYPOINTS;
            for (int i = 0; i < _wp_count; i++) {
                wp_obj = json_object_array_get_idx(wps_obj, i);
                struct json_object *f;
                json_object_object_get_ex(wp_obj, "lat", &f);
                double lat = f ? json_object_get_double(f) : 39.9;
                json_object_object_get_ex(wp_obj, "lon", &f);
                double lon = f ? json_object_get_double(f) : 116.4;
                json_object_object_get_ex(wp_obj, "height", &f);
                double h = f ? json_object_get_double(f) : 50.0;
                json_object_object_get_ex(wp_obj, "speed", &f);
                double spd = f ? json_object_get_double(f) : 5.0;
                _wp_queue[i].x = (lon - model_params.init_lon) / 0.00001;
                _wp_queue[i].y = (lat - model_params.init_lat) / 0.00001;
                _wp_queue[i].height = h;
                _wp_queue[i].speed = spd;
            }
            _wp_current = 0;
            _wp_active = 1;

            ModelU_t* U = model_get_input();
            if (U && _wp_count > 0) {
                MODEL_U_SET(U, cmd_x, _wp_queue[0].x);
                MODEL_U_SET(U, cmd_y, _wp_queue[0].y);
                MODEL_U_SET(U, cmd_z, _wp_queue[0].height);
                MODEL_U_SET(U, cmd_speed, _wp_queue[0].speed);
                MODEL_U_SET(U, cmd_mode, 4);
            }
            printf("[Cmd] load_mission: %d waypoints, mission=%s\n", _wp_count, _mission_id);
        }
        json_object_put(root);
        return 0;
    }

    /* ---- tune: generic dispatch via offset table ---- */
    if (cmd && strcmp(cmd, "tune") == 0) {
        ModelU_t* U = model_get_input();
        if (!U) { json_object_put(root); return -1; }
        json_object_object_get_ex(root, "params", &params_obj);
        int applied = 0;
        if (params_obj) {
            json_object_object_foreach(params_obj, key, val) {
                double value = json_object_get_double(val);
                model_u_set_by_name(U, key, value);
                applied++;
            }
        }
        printf("[Tune] %d param(s) applied\n", applied);
        json_object_put(root);
        return 0;
    }

    /* ---- takeoff / land / hover / move_position / move_velocity ---- */
    ModelU_t* U = model_get_input();
    if (!U) {
        printf("[Cmd] Model not loaded, ignoring '%s'\n", cmd ? cmd : "null");
        json_object_put(root);
        return -1;
    }

    if (cmd && strcmp(cmd, "takeoff") == 0) {
        _wp_active = 0;
        json_object_object_get_ex(root, "params", &params_obj);
        if (params_obj) {
            json_object_object_foreach(params_obj, key, val) {
                if (strcmp(key, "height") == 0) MODEL_U_SET(U, cmd_z, json_object_get_double(val));
            }
        }
        MODEL_U_SET(U, cmd_mode, 1);
        _last_cmd_mode_written = 1;
        printf("[Cmd] takeoff\n");
    } else if (cmd && strcmp(cmd, "land") == 0) {
        _wp_active = 0;
        MODEL_U_SET(U, cmd_mode, 2);
        _last_cmd_mode_written = 2;
        printf("[Cmd] land\n");
    } else if (cmd && strcmp(cmd, "hover") == 0) {
        _wp_active = 0;
        MODEL_U_SET(U, cmd_mode, 3);
        _last_cmd_mode_written = 3;
        printf("[Cmd] hover\n");
    } else if (cmd && strcmp(cmd, "move_position") == 0) {
        _wp_active = 0;
        json_object_object_get_ex(root, "params", &params_obj);
        if (params_obj) {
            json_object_object_foreach(params_obj, key, val) {
                if (strcmp(key, "x") == 0) MODEL_U_SET(U, cmd_x, json_object_get_double(val));
                else if (strcmp(key, "y") == 0) MODEL_U_SET(U, cmd_y, json_object_get_double(val));
                else if (strcmp(key, "height") == 0) MODEL_U_SET(U, cmd_z, json_object_get_double(val));
                else if (strcmp(key, "speed") == 0) MODEL_U_SET(U, cmd_speed, json_object_get_double(val));
            }
            MODEL_U_SET(U, cmd_mode, 4);
            printf("[Cmd] move_position\n");
        }
    } else if (cmd && strcmp(cmd, "move_velocity") == 0) {
        _wp_active = 0;
        json_object_object_get_ex(root, "params", &params_obj);
        if (params_obj) {
            json_object_object_foreach(params_obj, key, val) {
                if (strcmp(key, "vx") == 0) MODEL_U_SET(U, cmd_x, json_object_get_double(val));
                else if (strcmp(key, "vy") == 0) MODEL_U_SET(U, cmd_y, json_object_get_double(val));
                else if (strcmp(key, "vz") == 0) MODEL_U_SET(U, cmd_z, json_object_get_double(val));
                else if (strcmp(key, "duration") == 0) MODEL_U_SET(U, cmd_duration, json_object_get_double(val));
            }
            MODEL_U_SET(U, cmd_mode, 5);
            printf("[Cmd] move_velocity\n");
        }
    } else if (cmd && strcmp(cmd, "get_state") == 0) {
        printf("[Cmd] get_state\n");
    }
    json_object_put(root);
    return 0;
}

void* command_thread(void* arg) {
    char buffer[4096];
    while (running) {
        int n = udp_recv_command(buffer, sizeof(buffer));
        if (n > 0) parse_command(buffer);
        usleep(10000);
    }
    return NULL;
}

int main(int argc, char** argv) {
    printf("=== HIL Real-Time Core (V2 template) ===\n");
    printf("  Model: %s\n", MODEL_NAME);
    printf("  SLX:   %s\n", MODEL_SLX);
    printf("  Adapted: %d\n", MODEL_ADAPTED);

    struct sched_param param = { .sched_priority = 99 };
    if (sched_setscheduler(0, SCHED_FIFO, &param) == -1)
        perror("sched_setscheduler (run with sudo)");

    if (mlockall(MCL_CURRENT | MCL_FUTURE) == -1)
        perror("mlockall");

    hal_system_init();

    if (udp_init(UDP_CMD_PORT, UDP_STATUS_PORT) != 0) {
        fprintf(stderr, "[Error] UDP init failed\n");
        return -1;
    }

    model_initialize();

    pthread_t cmd_thread_id;
    pthread_create(&cmd_thread_id, NULL, command_thread, NULL);

    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);

    struct timespec next_time;
    clock_gettime(CLOCK_MONOTONIC, &next_time);
    uint64_t step_count = 0;
    printf("[Main] Starting 1ms loop...\n");

    while (running) {
        next_time.tv_nsec += STEP_NS;
        if (next_time.tv_nsec >= 1000000000) {
            next_time.tv_nsec -= 1000000000;
            next_time.tv_sec += 1;
        }
        clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &next_time, NULL);

        step_count++;

        if (step_count % 1000 == 0) {
            model_apply_pending_update(&argc, argv);
            if (model_is_loaded()) {
                model_initialized = 1;
            }
        }

        if (model_is_loaded() && model_initialized) {
            model_step();

            ModelY_t y;
            model_get_output(&y);

            /* ---- waypoint queue: check if reached current, advance ---- */
            if (_wp_active && _wp_count > 0 && _wp_current < _wp_count) {
                double px = MODEL_Y_GET(&y, pos_x, MODEL_DEFAULT_POS_X);
                double py = MODEL_Y_GET(&y, pos_y, MODEL_DEFAULT_POS_Y);
                double pz = MODEL_Y_GET(&y, pos_z, MODEL_DEFAULT_POS_Z);
                double dx = px - _wp_queue[_wp_current].x;
                double dy = py - _wp_queue[_wp_current].y;
                double dz = pz - _wp_queue[_wp_current].height;
                if ((dx*dx + dy*dy + dz*dz) < 1.0) {
                    _wp_current++;
                    ModelU_t* U = model_get_input();
                    if (U && _wp_current < _wp_count) {
                        MODEL_U_SET(U, cmd_x, _wp_queue[_wp_current].x);
                        MODEL_U_SET(U, cmd_y, _wp_queue[_wp_current].y);
                        MODEL_U_SET(U, cmd_z, _wp_queue[_wp_current].height);
                        MODEL_U_SET(U, cmd_speed, _wp_queue[_wp_current].speed);
                        MODEL_U_SET(U, cmd_mode, 4);
                        printf("[Waypoint] %d/%d reached\n", _wp_current, _wp_count);
                    } else {
                        _wp_active = 0;
                        printf("[Waypoint] All %d waypoints completed\n", _wp_count);
                    }
                }
            }

            /* ---- Fill FlightState_t from ModelY_t via macros ---- */
            current_state.version = 1;
            current_state.timestamp_us = step_count * 1000;
            current_state.pos_x = MODEL_Y_GET(&y, pos_x, MODEL_DEFAULT_POS_X);
            current_state.pos_y = MODEL_Y_GET(&y, pos_y, MODEL_DEFAULT_POS_Y);
            current_state.pos_z = MODEL_Y_GET(&y, pos_z, MODEL_DEFAULT_POS_Z);
            current_state.roll  = MODEL_Y_GET(&y, roll,  MODEL_DEFAULT_ROLL);
            current_state.pitch = MODEL_Y_GET(&y, pitch, MODEL_DEFAULT_PITCH);
            current_state.yaw   = MODEL_Y_GET(&y, yaw,   MODEL_DEFAULT_YAW);
            current_state.vel_x = MODEL_Y_GET(&y, vel_x, 0.0f);
            current_state.vel_y = MODEL_Y_GET(&y, vel_y, 0.0f);
            current_state.vel_z = MODEL_Y_GET(&y, vel_z, 0.0f);

            /* lat/lon/alt — may not be present in all models */
            current_state.lat = MODEL_Y_GET(&y, lat, 39.9);
            current_state.lon = MODEL_Y_GET(&y, lon, 116.4);
            current_state.alt = MODEL_Y_GET(&y, alt, 100.0);
            current_state.acc_x = MODEL_Y_GET(&y, acc_x, 0.0f);
            current_state.acc_y = MODEL_Y_GET(&y, acc_y, 0.0f);
            current_state.acc_z = MODEL_Y_GET(&y, acc_z, 0.0f);

            /* airborne flag */
            current_state.status_word = MODEL_Y_GET(&y, airborne, 0) ? 1 : 0;

            /* ---- angular velocity: diff of attitude / 100ms ---- */
            if (step_count % SEND_INTERVAL == 0) {
                float dt = SEND_INTERVAL * 0.001f;
                if (dt > 0.0f) {
                    current_state.ang_vel_p = (current_state.roll - _prev_roll) / dt;
                    current_state.ang_vel_q = (current_state.pitch - _prev_pitch) / dt;
                    current_state.ang_vel_r = (current_state.yaw - _prev_yaw) / dt;
                }
                _prev_roll = current_state.roll;
                _prev_pitch = current_state.pitch;
                _prev_yaw = current_state.yaw;

                /* ---- V2.0 flight_state ---- */
                current_state.flight_state = derive_flight_state(
                    current_state.status_word, current_state.pos_z, _wp_active);
            }

            current_state.battery_voltage = 24.5f;
            current_state.motor_speed_0 = 5000.0f;
            current_state.motor_speed_1 = 4800.0f;
            current_state.motor_speed_2 = 5200.0f;
            current_state.motor_speed_3 = 4900.0f;
            current_state.mission_id = 1;
            current_state.waypoint_index = _wp_active ? _wp_current : (_wp_count > 0 ? _wp_count : 0);
            current_state.flight_phase = 2;

            if (step_count % SEND_INTERVAL == 0) {
                udp_send_status(&current_state);
                udp_send_monitor(&current_state);  /* test port 9999 */
                hal_refmem_write(&current_state, sizeof(FlightState_t));
                hal_telemetry_send(&current_state, sizeof(FlightState_t));
            }
        }

        if (step_count % 1000 == 0 && model_is_loaded()) {
            printf("[Main] Step: %" PRIu64 ", Pos: (%.1f, %.1f, %.1f), Alt: %.1f, FS: %s\n",
                   step_count,
                   current_state.pos_x, current_state.pos_y, current_state.pos_z,
                   current_state.alt, flight_state_str(current_state.flight_state));
        }
    }

    model_terminate();
    hal_system_deinit();
    udp_close();
    pthread_cancel(cmd_thread_id);
    pthread_join(cmd_thread_id, NULL);

    printf("=== HIL Real-Time Core Stopped ===\n");
    return 0;
}
