/* Static wrapper around the generated ERT ABI.  Deployments never reload a
 * model in-process; the supervisor stops this executable before starting the
 * separately verified replacement. */
#include <stdio.h>
#include <string.h>

#if !defined(MODEL_RT_BRIDGE_HEADER)
#error "MODEL_RT_BRIDGE_HEADER must be generated by build_script.m"
#endif
#define HIL_STRINGIFY_(x) #x
#define HIL_STRINGIFY(x) HIL_STRINGIFY_(x)
#include HIL_STRINGIFY(MODEL_RT_BRIDGE_HEADER)
#include "model_rt_wrapper.h"

static int loaded = 0;

void model_initialize(void) { MODEL_INIT_FN(); loaded = 1; }
void model_step(void) { if (loaded) MODEL_STEP_FN(); }
void model_terminate(void) { if (loaded) { MODEL_TERM_FN(); loaded = 0; } }
ModelU_t* model_get_input(void) { return (ModelU_t*)&MODEL_U_VAR; }
void model_get_output(ModelY_t* out) { if (out) memcpy(out, &MODEL_Y_VAR, sizeof(*out)); }
int model_is_loaded(void) { return loaded; }
